### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by budaminof** [craftninja/exp-starter-api#34]
I have notice from working on the application build on top of your  :sparkles: AMAZING  :sparkles: starter api, that in the modal we are returning:
```js
const errors = await validate(properties);
  if (errors) {
    return { errors };
  }
```

We found that errors are being returned as an array of errors but with a 200 status code.

How to you feel about throwing the array of errors to ensure that we are throwing errors with the right status code? (those will be handled in the controller's try catch)

So in the validate function we will:

```js
  if (errors.length > 0) {
      throw errors;
  }
```

What do you think?

**Comment by craftninja** [comment]
The current pattern in this app is only giving 404s and 200s (or 503s from host if the server is down / upgrading).

* 404 - `doesn't exist` OR `doesn't exist FOR YOU (not authorized)`
* 200 - `you are allowed to be here and here is what I have to say`,  and maybe there are `{ errors: pileOfErrors }` that need to be sorted through...

There are a LOT of theories / patterns about what the "right" status codes are, and really as long as you DECIDE on a pattern and FOLLOW the pattern throughout the app, you are using the "right" status code. For some reason, sometimes this often makes developers very uncomfortable and yelly. If as a development team, you DECIDE on a new pattern, make sure that that pattern is used throughout the app, not just in the "new" place.

### 🚫 But why not `401 unauth` in addition to `404 not found`? Some details on something you did not ask... 
The pattern that is used in this app is the simplest that I have encountered, and I do love it's simplicity. The reason we only give 404s is to obscure what is *truly* `Not Found` and what is "Not Found for *you*, user" aka `Unauthorized` for specific logged in user or guest. You can see a "front end" version of this at GitHub. If you visit a private repo without being logged in, the user sees a 404 along with a login component. If you log in, you are allowed access IF you are allowed access. If you are not allowed access, you still get the 404, as if it is really not there. This is (AND SHOULD BE) **identical** behavior to an actual 404 (in the case of something really not existing). That way, malicious users cannot find out anything that they "shouldn't" about the shape of your app or the existence of information in the app. You are obscuring what is *really not there* and what some users *SHOULDN'T know exist*.

### 😍 I love it! How do I convince other developers this is ok? 

If you do like this pattern, and for help in "pushing back" to yelly uncomfortable developers who say we don't use the "right" status code: this *is* a pattern in use. It is the pattern used by Facebook Graph API. More details about how to choose are outlined in this article: https://blogs.dropbox.com/developers/2015/04/how-many-http-status-codes-should-your-api-use/

### 🚩 But I need more status codes! 

If you don't like this pattern, or find that some extra status codes would *really* make things easier, feel free to change it in your app! Remember to ask yourself, am I adding status codes because we really want to use them? Or am I adding status codes because I think that it's the "right" code to use? It will be hard to deprecate used status codes!

### 😒 Too Long, Didn't Read  

I would prefer to keep this starter app as simple as possible so that any user can choose their favorite pattern, including the simplest 200/404 version.

Thanks so much! I can't wait to hear about what you decide to use in your app!

**Comment by budaminof** [comment]
Emily- thank you for the detailed and informative answer! I will keep you update on what we decide 🙏
